spring.data.mongodb.uri=mongodb+srv://anilwhitecirclegroup_db_user:WhiteCircle2026@wcgwebsite.rimhtyl.mongodb.net/WhiteCircleDB?retryWrites=true&w=majority&appName=WCGWebsite
server.port=8081

# Email Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
# The Gmail address that will SEND the emails
spring.mail.username=anilwhitecirclegroup@gmail.com
# The 16-letter App Password you just generated (NO SPACES)
spring.mail.password=cocmyklsqheyzbbc
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true