# Server Configuration
server.port=8081

# Secure MongoDB Configuration
spring.data.mongodb.uri=${MONGO_URL}

# Secure Email Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
# Replace this with the actual Gmail address you are using to SEND the emails
spring.mail.username=anilwhitecirclegroup@gmail.com
spring.mail.password=${GMAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true